ALTER TABLE player ADD COLUMN forty_yard_dash double precision;
ALTER TABLE player ADD COLUMN bench_press double precision;
ALTER TABLE player ADD COLUMN vertical_jump double precision;
ALTER TABLE player ADD COLUMN broad_jump double precision;
ALTER TABLE player ADD COLUMN three_cone_drill double precision;
ALTER TABLE player ADD COLUMN twenty_yard_shuttle double precision;
ALTER TABLE player ADD COLUMN sixty_yard_shuttle double precision;
ALTER TABLE player ADD COLUMN hand_size double precision;
ALTER TABLE player ADD COLUMN arm_length double precision;